### PR TITLE
small screens menu accessibility

### PR DESCRIPTION
**Pull request by emiex**

### CODE REVIEW

**Comment by bonustrack** [comment]
@emiex I think the scrollbar should never be visible, can you hide it?

**Comment by emiex** [comment]
> @emiex I think the scrollbar should never be visible, can you hide it?

That only shows if you are dragging right or right if the tabs are more than what can fit on the mobile screen.

**Comment by bonustrack** [comment]
@emiex It doesn't look so sexy with the scrollbar visible, it doesn't have to be visible for user to be able to scroll it so we can remove it and keep the scroll. It's common way to navigate on mobile sites

**Comment by emiex** [comment]
> @emiex It doesn't look so sexy with the scrollbar visible, it doesn't have to be visible for user to be able to scroll it so we can remove it and keep the scroll. It's common way to navigate on mobile sites

Yes on a mobile screen it wont be showing, only on a pc browser responsive screen. In anycase updated again the scroller wont be showing at all on any screen from now on.

**Review by bonustrack — APPROVED** [review]
Looking great! Thank you for your contribution!

**Pull request merged**
