### PR TITLE
Create SHRIMP space

### PR DESCRIPTION
**Pull request by doomsayer817**
Add shrimp token

Fixes # .

Changes proposed in this pull request:
- 
- 
-

### CODE REVIEW

**Comment by bonustrack** [comment]
@doomsayer817 Are you in our Discord? There is few things missing to add a token, here is a guide to add a token: https://docs.snapshot.page

**Comment by doomsayer817** [comment]
@bonustrack Hi I already update logo and skin thx

**Comment by bonustrack** [comment]
@doomsayer817 Looking good! Can you resolve conflicts? Then i will merge your PR.

**Comment by doomsayer817** [comment]
@bonustrack I already resolve conflicts, please check thanks

**Pull request merged**
