### PR TITLE
Add grap namespace

### PR DESCRIPTION
**Pull request by GrapFinance**
Changes proposed in this pull request:
- Add GRAP namespace
- Add GRAP's skin

### CODE REVIEW

**Comment by bonustrack** [comment]
@GrapFinance Hi can you update the PR following the new guide here: https://docs.snapshot.page/guides/create-a-space

**Comment by GrapFinance** [comment]
@bonustrack Already got verify from trustwallet.

**Comment by bonustrack** [comment]
You need to make a new pull request with the new format see here: https://docs.snapshot.page/guides/create-a-space

**Comment by GrapFinance** [comment]
Got it.

**Pull request closed without merging**
