### PR TITLE
add ShillDAO space

### PR DESCRIPTION
**Pull request by iadpay**
Changes proposed in this pull request:
- add ShillDAO namespace
- add logo
- add skin

### CODE REVIEW

**Comment by bonustrack** [comment]
@iadpay Sorry we've changed the structure to store space data, now space have their own folder see: https://github.com/balancer-labs/snapshot/tree/develop/spaces can you have a look here: https://docs.snapshot.page/guides/create-a-space and update your PR?

**Comment by iadpay** [comment]
Thx for remind, I will update the PR soon.

**Comment by iadpay** [comment]
Hi @bonustrack , we have submit a new PR here https://github.com/balancer-labs/snapshot/pull/52, need review and merge pls.

**Comment by bonustrack** [comment]
This PR is not relevant anymore, i'm closing it.

**Pull request closed without merging**
