### PR TITLE
feat: issue#179 show user vote at the top

### LINKED ISSUE #179: Show your own vote on top of the list
If you casted a vote on a proposal you should see your vote on top of the vote list regardless of the voting power.

### PR DESCRIPTION
**Pull request by samuveth**
Fixes #179 

Changes proposed in this pull request:
- rearrange votes before they are sliced in visibleVotes()
- 
-

### CODE REVIEW

**Comment by bonustrack** [comment]
@samuveth Something seem to be broken with the vote, if you check here:
https://bafybeihmmytcnufl46lyufxofbrtdw6aiyrog7gxgpwglucmk5sb2sc3fa.on.fleek.co/#/dai/proposal/QmdNR3Eed8nmNPMciQkTznQfR98sDcXVbLpGqUZ996M8tk
You will not see the votes, there is an error in the console
Compare to the original here: https://demo.snapshot.page/#/dai/proposal/QmdNR3Eed8nmNPMciQkTznQfR98sDcXVbLpGqUZ996M8tk

**Comment by samuveth** [comment]
@bonustrack Yeah, I missed something there. I think I know what it is

**Comment by samuveth** [comment]
@bonustrack should be fixed now.

**Review by bonustrack — APPROVED** [review]
Looks good!

**Pull request merged**
