### PR TITLE
Add Toast.finance

### PR DESCRIPTION
**Pull request by Cryptoastio**
Changes proposed in this pull request:
- Toast.finance asset namespace
- Toast.finance logo

### CODE REVIEW

**Comment by bonustrack** [comment]
@Cryptoastio Hi! Some steps are missing, please have a look here the guide: https://docs.snapshot.page/guides/create-a-space

**Comment by DChiuch** [comment]
> @Cryptoastio Hi! Some steps are missing, please have a look here the guide: https://docs.snapshot.page/guides/create-a-space

Hey, which step is missing? Do you mean step 7?

**Comment by Cryptoastio** [comment]
> @Cryptoastio Hi! Some steps are missing, please have a look here the guide: https://docs.snapshot.page/guides/create-a-space

Hey, which step is missing? Do you mean step 7?

**Comment by bonustrack** [comment]
Yes @Cryptoastio now i can see it looks good can you merge conflict?

**Comment by Cryptoastio** [comment]
> Yes @Cryptoastio now i can see it looks good can you merge conflict?

Done

**Comment by bonustrack** [comment]
@Cryptoastio Sorry we've changed the structure to store space data, now space have their own folder see: https://github.com/balancer-labs/snapshot/tree/develop/spaces can you have a look here: https://docs.snapshot.page/guides/create-a-space and update your PR?

**Comment by Cryptoastio** [comment]
> @Cryptoastio Sorry we've changed the structure to store space data, now space have their own folder see: https://github.com/balancer-labs/snapshot/tree/develop/spaces can you have a look here: https://docs.snapshot.page/guides/create-a-space and update your PR?

Okay, how are we looking now?

**Comment by bonustrack** [comment]
@Cryptoastio nope, you need to merge last change from develop branch in your PR

**Comment by Cryptoastio** [comment]
Thought I did merge .. I merged again, is it okay now?

Thanks

**Comment by bonustrack** [comment]
@Cryptoastio It still not good, this code shouldn't be in your PR: https://github.com/balancer-labs/snapshot/pull/42/files#diff-adcca81d61eb9f6006396494f1e3ef9f

**Comment by bonustrack** [comment]
@Cryptoastio Almost there! Now can you delete this file? https://github.com/balancer-labs/snapshot/pull/42/files#diff-f3b63f6128786cdf4b88cff60ad4bb79

**Comment by Cryptoastio** [comment]
Oops - got it

**Review by bonustrack — APPROVED** [review]
Looking good!

**Pull request merged**
