### PR TITLE
Dollar Protocol Add Space

### PR DESCRIPTION
**Pull request by satoshinate**
Fixes # .

Changes proposed in this pull request:
- https://dollarprotocol.com
- 
-

### CODE REVIEW

**Review by e-asia — COMMENTED** [review]
- The css selector should be dollarProtocol instead of name
- The space.png image is missing

**Comment by bonustrack** [comment]
Please lowercase the space key and css class

**Comment by satoshinate** [comment]
@bonustrack @e-asia, we deleted skin.scss and added space.png image.

let me know if it is good to merge.

**Comment by bonustrack** [comment]
@satoshinate Sorry but we've changed the repository for the spaces can you make a PR here instead: https://github.com/bonustrack/snapshot-spaces ? Have a look here on the updated docs: https://docs.snapshot.page/guides/create-a-space I'm closing this PR for now feel free to reach our Discord for help.

**Pull request closed without merging**
